@startuml

/'
  図の中で目立たせたいエンティティに着色するための
  色の名前（定数）を定義します。
'/
!define MAIN_ENTITY #E2EFDA-C6E0B4
!define MAIN_ENTITY_2 #FCE4D6-F8CBAD

/' 他の色も、用途が分りやすいように名前をつけます。 '/
!define METAL #F2F2F2-D9D9D9
!define MASTER_MARK_COLOR AAFFAA
!define TRANSACTION_MARK_COLOR FFAA00

/'
  デフォルトのスタイルを設定します。
  この場合の指定は class です。entity ではエラーになります。
'/
skinparam class {
    BackgroundColor METAL
    BorderColor Black
    ArrowColor Black
}

package "スキルマップシェア DBモデル" as atmedia {
      entity "仮登録アカウント(TemporaryAccount)" as TemporaryAccount <<E,TRANSACTION_MARK_COLOR>> MAIN_ENTITY {
        +id [PK]
        --
        email
        email_verfication_token
        token_expired_datetime
        created_datetime
        updated_datetime
      }
      entity "ユーザ(Users)" as Users <<E, TRANSACTION_MARK_COLOR>> MAIN_ENTITY {
          +id [PK] : String
          --
          email
          user_application_id
          user_display_name
          created_datetime
          updated_datetime
      }
      entity "ユーザのアイコン(UserIcons)" as UserIcons <<E, TRANSACTION_MARK_COLOR>>MAIN_ENTITY {
        +id [PK]
        --
        user_id [FK]
        file_path
      }
      entity "ユーザの連携SNSアカウント(UserSnsAccounts)" as UserSnsAccounts <<E, TRANSACTION_MARK_COLOR>> MAIN_ENTITY {
        +id [PK]
        --
        user_id [FK]
        relationable_sns_type_id [FK]
      }
      entity "連携できるSNSアカウント(RelationableSnsTypes)" as RelationableSnsTypes <<E, MASTER_MARK_COLOR>> MAIN_ENTITY_2 {
        +id
        --
        name
      }
    TemporaryAccount --do-- Users
    Users --o| UserIcons
    Users -ri-o{ UserSnsAccounts
    RelationableSnsTypes -do-o{ UserSnsAccounts
    note top of TemporaryAccount : 仮登録テーブルとユーザテーブルに\n同じメールアドレスのデータが\n存在しないこと
    note top of Users : SNSアカウントの場合でも、メールアドレスが同じの場合は登録ができない\n idはFireBaseのuuidを利用する
}
@enduml
