spring:
  profiles: local
  messages:
    cache-duration: -1
  datasource:
    url: "jdbc:mysql://localhost:3306/skill_map_db_development"
    username: root
    password: password
  flyway:
    enable: true
    url: "jdbc:mysql://localhost:3306/skill_map_db_development"
    user: root
    password: password
    baseline-on-migrate: true
    placeholder-replcement: false
    locations: "classpath:db/migration"
  logging:
    level:
      org.springframework: INFO
      org.springframework.jdbc: INFO
      org.thymeleaf: INFO
      com.proatmedia: DEBUG
  mail:
    host: "localhost"
    port: 1025
    auth: false
    connectiontimeout: 10000
    timeout: 10000
    writetimeout: 10000
